### ISSUE TITLE
5주차 마무리 Flowchart

### ISSUE THREAD

**Issue by jeontigger** [AssortRockStudy/WinAPI#21]
## 심심한 사람은 UML도 그려보자

- https://app.diagrams.net/
- www.figma.com/
로 그릴수도 있음

**Comment by jwkim395** [comment]
![Image](https://github.com/AssortRockStudy/WinAPI/assets/142799775/d4f04325-2ea6-434d-8f9f-875b77d64f56)

**Comment by oljindudol** [comment]
![Image](https://github.com/AssortRockStudy/WinAPI/assets/82567430/066d7033-ec7d-4d9d-b182-905650262936)



![Image](https://github.com/AssortRockStudy/WinAPI/assets/82567430/6f6894da-443a-4b6b-a44f-275c3a9b1073)

**Comment by superozing** [comment]
https://transparent-watercress-5cc.notion.site/ReCap-ccbf633a7bba4875ba5de1e7b3615ee1?pvs=4
늦어서 여기에 완성되고 올릴게

**Comment by uzzzzin** [comment]
![Image](https://github.com/AssortRockStudy/WinAPI/assets/105213685/8bb00d81-7fd5-4e23-930a-e1a26828f871)



![Image](https://github.com/AssortRockStudy/WinAPI/assets/105213685/e3069887-b091-4348-8f80-eb8ec7f1a46e)

**Comment by zkzkzkzkzkzz** [comment]
![Image](https://github.com/AssortRockStudy/WinAPI/assets/104834876/1497d34b-1569-42d1-b007-70c466c03733)

**Comment by zkzkzkzkzkzz** [comment]
![Image](https://github.com/AssortRockStudy/WinAPI/assets/104834876/f88828e5-1165-4e7b-8e0e-cf7e0805c883)
