### ISSUE TITLE
캐릭터 생성과 움직임

### ISSUE THREAD

**Issue by jeontigger** [AssortRockStudy/WinAPI#4]
## 캐릭터를 생성하고 움직여보자!
- [x] 재원
- [x] 민서
- [x] 진우
- [x] 진
- [x] 진영
- [x] 인호
- [x] 창희
-------
# 꼭 WinAPI 레포에서 작업
# 중간 커밋 필수 타이밍!!이자 요구사항 기능
0. 강사님 코드는 전부 구현
1. 플레이어 객체 생성(검정색 사각형)
2. 플레이어가 아닌 다른 객체 생성(빨간색 원)
3. 플레이어는 wasd로 상 하 좌 우 움직임 입력
4. 플레이어가 아닌 객체는 wasd로 하 상 우 좌 로 플레이어와는 정 반대로 움직임
5. 색상 펜과 브러시를 관리하는 팔레트 객체 구현
6. 처음부터 생성, 소멸자에서 해제
# 9월 6일 추가
- 키매니저를 통해 이동 구현!

**Comment by oljindudol** [comment]
1빠
